services:
  # C++ template node (default)
  cpp_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-template:humble
    container_name: ros_template_node
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    healthcheck:
      test: >
        bash -c "
        source /opt/ros/humble/setup.bash &&
        ros2 node list | grep -q template_node &&
        ros2 topic list | grep -q /template/status &&
        ros2 topic echo /template/status --once >/dev/null 2>&1
        "
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    command: >
      ros2 launch ros_template_node template.launch.py
      publish_rate:=2.0
      topic_prefix:=template

  # Python template node
  python_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-template:humble
    container_name: py_template_node
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    stdin_open: true
    tty: true
    profiles:
      - python
    healthcheck:
      test: >
        bash -c "
        source /opt/ros/humble/setup.bash &&
        ros2 node list | grep -q py_template_node &&
        ros2 topic list | grep -q /py_template/status &&
        ros2 topic echo /py_template/status --once >/dev/null 2>&1
        "
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    command: >
      ros2 launch py_template_node py_template.launch.py
      publish_rate:=1.5
      topic_prefix:=py_template

  # Foxglove bridge for visualization (separate service)
  foxglove:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-template:humble
    container_name: foxglove_bridge
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    stdin_open: true
    tty: true
    profiles:
      - foxglove
    healthcheck:
      test: >
        bash -c "
        source /opt/ros/humble/setup.bash &&
        ros2 node list | grep -q foxglove_bridge
        "
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    command: >
      ros2 launch foxglove_bridge foxglove_bridge_launch.xml
      port:=8765