services:
  ros_template:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-template:humble
    container_name: ros_template_node
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    healthcheck:
      test: >
        bash -c "
        ros2 node list | grep -q template_node &&
        ros2 topic list | grep -q /template/status &&
        ros2 topic echo /template/status --once --timeout 5 >/dev/null 2>&1
        "
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    command: >
      ros2 launch ros_template_node template.launch.py
      publish_rate:=2.0
      topic_prefix:=template
      enable_foxglove:=true
      foxglove_port:=8765

  # Python template node
  py_template:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-template:humble
    container_name: py_template_node
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    stdin_open: true
    tty: true
    profiles:
      - python
    healthcheck:
      test: >
        bash -c "
        ros2 node list | grep -q py_template_node &&
        ros2 topic list | grep -q /py_template/status &&
        ros2 topic echo /py_template/status --once --timeout 5 >/dev/null 2>&1
        "
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    command: >
      ros2 launch py_template_node py_template.launch.py
      publish_rate:=1.5
      topic_prefix:=py_template
      enable_foxglove:=false

  # Optional: Fast C++ instance with different parameters
  ros_template_fast:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-template:humble
    container_name: ros_template_node_fast
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    stdin_open: true
    tty: true
    profiles:
      - multi-node
    healthcheck:
      test: >
        bash -c "
        ros2 node list | grep -q template_node &&
        ros2 topic list | grep -q /template_fast/status &&
        ros2 topic echo /template_fast/status --once --timeout 5 >/dev/null 2>&1
        "
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    command: >
      ros2 launch ros_template_node template.launch.py
      publish_rate:=10.0
      topic_prefix:=template_fast
      enable_foxglove:=false

  # Both C++ and Python nodes together
  dual_nodes:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-template:humble
    container_name: dual_template_nodes
    network_mode: host
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    stdin_open: true
    tty: true
    profiles:
      - dual
    healthcheck:
      test: >
        bash -c "
        ros2 node list | grep -q template_node &&
        ros2 node list | grep -q py_template_node &&
        ros2 topic list | grep -q /cpp_template/status &&
        ros2 topic list | grep -q /py_template/status &&
        ros2 topic echo /cpp_template/status --once --timeout 5 >/dev/null 2>&1 &&
        ros2 topic echo /py_template/status --once --timeout 5 >/dev/null 2>&1
        "
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 20s
    command: >
      bash -c "
      ros2 launch ros_template_node template.launch.py 
      publish_rate:=2.0 topic_prefix:=cpp_template enable_foxglove:=true &
      ros2 launch py_template_node py_template.launch.py 
      publish_rate:=1.5 topic_prefix:=py_template enable_foxglove:=false &
      wait
      "