name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  ROS_DISTRO: humble

jobs:
  docker-test:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and test Docker
      run: |
        # Build image
        docker build -t ros-template:humble .
        
        # Test default profile with health monitoring
        docker compose up -d cpp_node
        sleep 20
        
        # Check container is healthy
        docker exec ros_template_node bash -c "source /opt/ros/humble/setup.bash && ros2 node list" | grep -q template_node
        docker exec ros_template_node bash -c "source /opt/ros/humble/setup.bash && ros2 topic list" | grep -q "/template/status"
        docker exec ros_template_node bash -c "source /opt/ros/humble/setup.bash && timeout 10 ros2 topic echo /template/status --once" >/dev/null 2>&1
        
        echo "✅ Docker health monitoring working"
        docker compose down
  
  code-quality:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install linting tools
      run: |
        sudo apt-get update && sudo apt-get install -y clang-format
        pip3 install black
    
    - name: Check C++ formatting
      run: |
        find src/ros_template_node -name "*.cpp" -o -name "*.hpp" | \
          xargs clang-format --dry-run --Werror
    
    - name: Check Python formatting
      run: |
        python3 -m black --check src/py_template_node/
